### ISSUE TITLE
Q: Is it possible to scroll through the result?

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [rcarriga/vim-ultest#40]
Hi,

First of all thanks for the plugin, I started using and I really like it.

I had aquestion about tests that have very long output e.g. tests in typescript for the front end that generate a html body when they fail.

When I run a test similar to the aforementioned one, I can see some of the output but not all of it and I couldn't figure out how to check the rest of the output since I don't know how to scroll through the output of a test.

I'm not using any configuration for either vim-test or vim-ultest. I'm using them out of the box

If you need any more input please let me know.

Thanks in advance.

**Comment by rcarriga** [comment]
Thanks for the feedback 😄 

You can jump to the output window in two ways:
1. Using a mapping in the test file to use `<Plug>(ultest-summary-jump)`
2. Using the `jumpto` mapping in the summary window while on a failed test/namespace (default is `<CR>`)

Once in the window, you are within a `less` session so just use `less` mappings to navigate e.g. j/k to scroll by line.
This will be changing soon for neovim-nightly since support for processing ANSI escape codes was added so that it will be a regular neovim buffer rather than a `less` session

**Comment by AlaaSaadAbdo** [comment]
Thanks for getting back to me so quickly :) 

I'll try what you suggested and you can close the issue if you want. I might contribute to the documentation once the support for ANSI escape codes is in nvim if I find that useful.

**Comment by rcarriga** [comment]
In case you missed it in the REAME the output window can handle ANSI codes, you just have to tell your runner to always output colour so for example with jest
```vim
let test#javascript#jest#options = "--color=always"
```
and the output window will handle them. The test runner by default won't output colour because it can't detect a PTY, this is something I have in the works to handle as well but it's quite complex so will take some time.

The handling of ANSI I mentioned was only just being able to display it without the help of `less`
