### ISSUE TITLE
Dumb question, what am I doing wrong?

### ISSUE THREAD

**Issue by ricbermo** [rcarriga/vim-ultest#85]
**Describe the bug**
First that all, thanks for putting together this amazing plugin.

That being said, IDK if this is a bug report, most like it is not, but it seems that my config is not working somehow. I'm gonna ommit the other details, hopefully that doesn't offend you 😅 .

This is my config,

```lua
local g = vim.g

g.ultest_use_pty = 1
g.ultest_output_on_line = 0
g.ultest_fail_sign = ''

g['test#strategy'] = "kitty"
g['test#preserve_screen'] = 0
g['test#javascript#jest#options'] = "--color=always"
```
And this is how I'm using it
```lua
  use {
    'rcarriga/vim-ultest',
    requires = {'vim-test/vim-test'},
    run = ':UpdateRemotePlugins',
    config = function() require('config.testing') end,
    event = 'BufEnter',
  }
```
For some reason, I'm still seeing the output when the cursor is on top of the line and the `fail` icon is still the default one.

![image](https://user-images.githubusercontent.com/2601363/146202402-97b3ee9f-58a0-4b7d-ba07-d7c1eeb2d945.png)

Please let me know if you want me to add more details. I'll be happy to.

**Comment by rcarriga** [comment]
The problem is this line
```lua
    config = function() require('config.testing') end,
```
Packer will run this *after* loading the plugin. This works for lua plugins which use a `setup` function but traditional vimscript plugins run their setup upon loading and so all of the values are read before your config has run. You need to set these values before loading. You can do this by using the `setup` option of packer rather than `config`.

**Comment by ricbermo** [comment]
That was it. Thanks so much!!
